# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7e3cd5337373c5b28a1d4bfc51fa96a3cce9a8aa77a7d67c206b99f6ed40fd8916273d1b5b64136a3103f3d40e9200db940a15ef364c0b1b565ab0869832560

test:
  secret_key_base: 76c8e30355f703dbb3d32eea021bb2d8c7f03e0743d13d6957db95a164643753a91482b062db2de8cc8765fc3589338dafc11aa955e49d9bfc0e4d5c87fd813f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
